# Generated by Django 2.1.7 on 2020-01-05 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_gallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name_plural': 'Galleries'},
        ),
    ]
