# Generated by Django 2.1.7 on 2020-01-05 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_auto_20200105_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='status',
            field=models.CharField(blank=True, choices=[('N', 'Nature'), ('M', 'Maternity'), ('B', 'Baby'), ('E', 'Engagement')], default='M', help_text='Book availability', max_length=1),
        ),
    ]
