# Generated by Django 2.1.7 on 2020-01-05 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_gallery_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='status',
            field=models.CharField(blank=True, choices=[('Nature', 'Nature'), ('Maternity', 'Maternity'), ('Baby', 'Baby'), ('Engagement', 'Engagement')], default='M', help_text='Book availability', max_length=1),
        ),
    ]
