# Generated by Django 2.1.7 on 2020-01-05 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_auto_20200105_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'Nature'), ('2', 'Maternity'), ('3', 'Baby'), ('4', 'Engagement')], default='1', max_length=1),
        ),
    ]
