# Generated by Django 2.1.7 on 2020-05-25 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0008_auto_20200105_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='photo',
            field=models.FilePathField(path='images/'),
        ),
    ]
